version: '3'
services:
  dev-postgres:
    image: postgres:14.4-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: shogura
      POSTGRES_PASSWORD: shogura_dev
      POSTGRES_DB: todo-nest
    restart: always
    networks:
      - todo-nest
networks:
  todo-nest:
